name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: |
          npm install
      - name: build ui
        run: |
          npm run build
      - name: Commit/Push build to docs branch
        run: |
          git config --global user.name 'henloh'
          git config --global user.email 'henloh@users.noreply.github.com'
          git add docs -f
          git commit -m "build"
          git push origin HEAD:docs --force
